apiVersion: v1
kind: Service
metadata:
  name: smsapi
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: smsapi
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: smsapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: smsapi
    spec:
      containers:
      - name: smsapi
        image: fiorix/sms-api-server
        ports:
        - containerPort: 8080
        env:
        - name: SMPP_USER
          value: foobar
        - name: SMPP_PASSWD
          value: c-krit
        args:
        - --tls
        - --smpp=smpp-provider-hostname:port
